In [1]:
'''
First, we will import everything we need. We will also define a couple
of useful functions.
'''
import torch
from torch import nn

# This is a function that prints the number of trainable parameters 
# of a model.
def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

# This functions prints all parameters (and their gradients) of a model.
def print_parameters(model):
    for name, param in model.named_parameters():
        print(name)
        print(param.data)
        print(param.grad)

In [5]:
'''
Now, we initialize our RNN.
'''
herRNN = nn.RNN(3, 1, nonlinearity='relu', bias=False)

In [6]:
count_parameters(herRNN)

4

In [7]:
# We set herRNN's weights and to those from our example.
for name, param in herRNN.named_parameters():
    print(name)
    print(param)
    if name == 'weight_ih_l0':
        param.data = torch.tensor([[1., 5., 3.]])
    else:
        param.data = torch.tensor([[7.]])
    print(param)

weight_ih_l0
Parameter containing:
tensor([[ 0.7954,  0.6342, -0.6827]], requires_grad=True)
Parameter containing:
tensor([[1., 5., 3.]], requires_grad=True)
weight_hh_l0
Parameter containing:
tensor([[-0.5628]], requires_grad=True)
Parameter containing:
tensor([[7.]], requires_grad=True)


In [8]:
# Define the input from our example and compute the RNN's hidden state for it.
x = torch.tensor([[3., 2., 1.]])
h_0 = torch.tensor([[1.]])

output, h_T = herRNN(x, h_0)  # output contains all hidden states; hn is the last one
print(output)

tensor([[23.]], grad_fn=<SqueezeBackward1>)
